### ISSUE TITLE
http-parser-js causes node8.5 to crash with ERR_INVALID_ASYNC_ID error

### ISSUE THREAD

**Issue by japrescott** [creationix/http-parser-js#40]
In node8.5, using http-parser-js crashes with the following error

`RangeError [ERR_INVALID_ASYNC_ID]: Invalid asyncId value: false                                                                                                                                                                                                     [34/9221]
    at emitDestroyScript (async_hooks.js:439:7)
    at freeParser (_http_common.js:220:7)
    at socketOnClose (_http_server.js:401:5)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:545:12)
`

**Comment by Jimbly** [comment]
Fix published to NPM in v0.4.8
